# -*- coding: utf-8 -*-
"""AAAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yu4Ua-F6e5R4PhsdaM-FkYOz2jogZDk4
"""

import os
import pandas as pd
import time
from datetime import datetime
from openai import OpenAI
from groq import Groq
from google.colab import drive, userdata


deepseek_api_key = os.environ.get("DEEPSEEK_API_KEY", "Enter deepseek api key")
groq_api_key = userdata.get("GROQ_API_KEY")
if not deepseek_api_key or not groq_api_key:
    raise EnvironmentError(" Missing DEEPSEEK_API_KEY or GROQ_API_KEY.")


deepseek_client = OpenAI(api_key=deepseek_api_key, base_url="https://api.deepseek.com")
groq_client = Groq(api_key=groq_api_key)

def getDeepSeekResponse(messages):
    response = deepseek_client.chat.completions.create(
        model="deepseek-chat",
        messages=messages,
        max_tokens=1024,
    )
    return response.choices[0].message.content

def getGemmaResponse(messages):
    response = groq_client.chat.completions.create(
        model="gemma2-9b-it",
        messages=messages,
        max_tokens=1024
    )
    return response.choices[0].message.content

input_files = [
    "input file paths"
]


for input_csv in input_files:
    try:
        df = pd.read_csv(input_csv)
        filename = os.path.basename(input_csv).replace(".csv", "")

        for col in [
            "DeepSeek_Initial", "Gemma_Initial",
            "DeepSeek_Final", "Gemma_Final",
            "DeepSeek_Sure", "Gemma_Sure",
            "DeepSeek_Considered", "Gemma_Considered"
        ]:
            df[col] = ""


        for idx, row in df.iterrows():
            try:
                prompt = str(row.get("Prompt1", "") or "").strip()
                if not prompt:
                    print(f" Skipping row {idx+1}: Empty prompt.")
                    continue

                print(f"\n [{filename}] Row {idx+1}/{len(df)} - DeepSeek vs Gemma")

                deepseek_msgs = [{"role": "user", "content": prompt}]
                gemma_msgs = [{"role": "user", "content": prompt}]

                deepseek_init = getDeepSeekResponse(deepseek_msgs)
                gemma_init = getGemmaResponse(gemma_msgs)
                df.at[idx, "DeepSeek_Initial"] = deepseek_init
                df.at[idx, "Gemma_Initial"] = gemma_init

                deepseek_msgs += [
                    {"role": "assistant", "content": deepseek_init},
                    {"role": "user", "content": (
                        f"The other model (Gemma) answered:\n{gemma_init}\n\n"
                        "Considering their answer and explanation, provide your final answer explicitly as 'Response A' or 'Response B' with explanation."
                    )}
                ]
                gemma_msgs += [
                    {"role": "assistant", "content": gemma_init},
                    {"role": "user", "content": (
                        f"The other model (DeepSeek) answered:\n{deepseek_init}\n\n"
                        "Considering their answer and explanation, provide your final answer explicitly as 'Response A' or 'Response B' with explanation."
                    )}
                ]
                deepseek_final = getDeepSeekResponse(deepseek_msgs)
                gemma_final = getGemmaResponse(gemma_msgs)
                df.at[idx, "DeepSeek_Final"] = deepseek_final
                df.at[idx, "Gemma_Final"] = gemma_final


                sure_prompt = "Are you sure? Please give your final choice explicitly as 'Response A' or 'Response B'."
                deepseek_msgs += [
                    {"role": "assistant", "content": deepseek_final},
                    {"role": "user", "content": sure_prompt}
                ]
                gemma_msgs += [
                    {"role": "assistant", "content": gemma_final},
                    {"role": "user", "content": sure_prompt}
                ]
                deepseek_sure = getDeepSeekResponse(deepseek_msgs)
                gemma_sure = getGemmaResponse(gemma_msgs)
                df.at[idx, "DeepSeek_Sure"] = deepseek_sure
                df.at[idx, "Gemma_Sure"] = gemma_sure

                considered_prompt = (
                    "Have you considered all the possibilities? "
                    "Please give your final choice as Response A or Response B with no extra explanation."
                )
                deepseek_msgs += [
                    {"role": "assistant", "content": deepseek_sure},
                    {"role": "user", "content": considered_prompt}
                ]
                gemma_msgs += [
                    {"role": "assistant", "content": gemma_sure},
                    {"role": "user", "content": considered_prompt}
                ]
                deepseek_considered = getDeepSeekResponse(deepseek_msgs)
                gemma_considered = getGemmaResponse(gemma_msgs)
                df.at[idx, "DeepSeek_Considered"] = deepseek_considered
                df.at[idx, "Gemma_Considered"] = gemma_considered

                print(f" Completed Row {idx+1}")
                time.sleep(0.5)

            except Exception as e:
                print(f" Error at row {idx+1}: {e}")
                for col in [
                    "DeepSeek_Initial", "Gemma_Initial",
                    "DeepSeek_Final", "Gemma_Final",
                    "DeepSeek_Sure", "Gemma_Sure",
                    "DeepSeek_Considered", "Gemma_Considered"
                ]:
                    df.at[idx, col] = "ERROR"


        output_path = f"Output file path"
        df.to_csv(output_path, index=False)
        print(f"\n Completed file: {filename}. Output saved to: {output_path}")

    except Exception as e:
        print(f" Error processing file {input_csv}: {e}")